server:
    port: 8081
    address: localhost

spring:
    profiles:
        active: dev

    datasource:
            dataSourceClassName: org.h2.Driver
            url: jdbc:h2:mem:pathfinder;DB_CLOSE_DELAY=-1
            databaseName:
            serverName:
            username:
            password: