server:
    port: 8081
    address: localhost

spring:
    profiles:
        active: dev

    datasource:
##            dataSourceClassName: org.h2.Driver
##            url: jdbc:h2:mem:pathfinder;DB_CLOSE_DELAY=-1
#            dataSourceClassName: com.mysql.jdbc.Driver
#            url: jdbc:mysql://localhost:3306/test
            dataSourceClassName: org.hsqldb.jdbcDriver
            url: jdbc:hsqldb:file:pathfinderDb
#            databaseName:
#            serverName:
#            username: test
#            password: test
    jpa:
            show-sql: true
            hibernate:
              ddl-auto: validate

flyway:
  initOnMigrate: true