server:
    port: 8686
    address: localhost

spring:
    profiles:
        active: prod

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test
        username:
        password: